name: projet-is
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # Python
  - python=3.10
  - pip

  # Core ML/Data Science
  - numpy # Laisser conda choisir la version compatible
  - pandas
  - scipy
  - scikit-learn
  - nltk
  - spacy # Laisser conda choisir
  - pytorch
  - transformers
  - sympy=1.13.1
  - thinc # Laisser conda choisir en fonction de spacy

  # Web & API
  - flask
  - requests
  - fastapi
  - uvicorn
  - whitenoise
  - flask-cors
  - starlette
  - a2wsgi
  - asgiref

  # Utilities
  - pydantic
  - python-dotenv
  - cryptography
  - tqdm
  - pyyaml
  - regex

  # Plotting & Graphing
  - matplotlib
  - seaborn
  - statsmodels
  - networkx
  - pyvis

  # Java Bridge
  - jpype1

  # Logic & Reasoning
  - clingo

  # Testing
  - pytest
  - pytest-cov
  - pytest-mock
  - pytest-asyncio
  - coverage
  - unidecode

  # La section pip est pour les paquets non disponibles ou problématiques sur Conda
  - pip:
    - semantic-kernel>=1.33.0
    - flask_socketio>=5.3.6
    - playwright
    - pytest-playwright
    - psutil